### ISSUE TITLE
Raspbian buster version

### ISSUE THREAD

**Issue by cleufven** [DaleFarnsworth/g90updatefw#1]
Hi,

Is it possible to get a compiled version for Raspbian buster?

Thank you,
Claes

**Comment by DaleFarnsworth** [comment]
I put a linux/arm executable in https://www.farnsworth.org/dale/g90updatefw/downloads/linux/arm/  I think that should work for Raspbian buster, though I haven't tried it.  I made some other linux and darwin variants as well.  Please test on buster and let me know how it goes.

**Comment by cleufven** [comment]
Thank you for the quick response!

I tried to run the arm version on my buster installation but I am sorry to say it did not work.
`
pi@portable:~/Downloads $ wget https://www.farnsworth.org/dale/g90updatefw/downloads/linux/arm/g90updatefw
--2020-06-16 22:34:54--  https://www.farnsworth.org/dale/g90updatefw/downloads/linux/arm/g90updatefw
Resolving www.farnsworth.org (www.farnsworth.org)... 198.74.58.51
Connecting to www.farnsworth.org (www.farnsworth.org)|198.74.58.51|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1601536 (1.5M) [application/octet-stream]
Saving to: ‘g90updatefw’

g90updatefw              100%[=================================>]   1.53M   198KB/s    in 8.1s    

2020-06-16 22:35:03 (194 KB/s) - g90updatefw saved [1601536/1601536]

pi@portable:/Downloads $ file g90updatefw 
g90updatefw: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=bikvvVxVTlexdWhivToL/DJ0XsnMkuUxP196vAbp1/S0KBEfX6wv-NvkfvsVuU/xTQZP_1cImW_koH8MxEB, stripped
pi@portable:/Downloads $ chmod +x g90updatefw 
pi@portable:/Downloads $ ./g90updatefw 
-bash: ./g90updatefw: cannot execute binary file: Exec format error
pi@portable:/Downloads $ sha256sum g90updatefw 
6a494959f92adb37a28e8621a19f150000c04495eda82334c24e1feeb453d139  g90updatefw
`

**Comment by DaleFarnsworth** [comment]
Yes.  Sorry about that.  I had an error in how I specified the architecture in the Makefile.  I have confirmed that https://www.farnsworth.org/dale/g90updatefw/downloads/linux/arm/g90updatefw is now a mips executable.  Please try again.

**Comment by cleufven** [comment]
Thank you for the update now it works perfectly! I test to upgrade from version 1.74 build unknown to version 1.74 build 4 without any issues on a Raspberry Pi3 model B+ with Raspbian Buster 10.4 with kernel 4.19.118-v7+ using an original FTDI ttl-232r-3v3-aj CAT cabel that works better then the supplied CAT cabel.

**Comment by DaleFarnsworth** [comment]
Thank you.
