### ISSUE TITLE
Windows defender reporting malware on G90updatefw.exe for i386

### ISSUE THREAD

**Issue by glebovitz** [DaleFarnsworth/g90updatefw#3]
I tried to download G90updatefw.exe from https://www.farnsworth.org/dale/g90updatefw/downloads/windows/386/, but it was blocked by windows defender because it had a trojan virus. I downloaded the amd64 version, but did not run into any issues.

Environment:
OS Name	Microsoft Windows 10 Pro
Version	10.0.19041 Build 19041
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 2208 Mhz, 6 Core(s), 12 Logical Processor(s)
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.488"
Browser Google Chrome Version 87.0.4280.66 (Official Build) (64-bit)

The attached PNG contains a screenshot from windows defender.

<img width="598" alt="G90 update fw screenshot" src="https://user-images.githubusercontent.com/1685230/100475228-9d844200-30b0-11eb-8caf-6a363593567d.png">

**Comment by DaleFarnsworth** [comment]
Hmm. I apologize for not responding sooner. I just noticed this issue today. I am quite confident that the g90updatefw binaries that I generated do not contain a trojan or virus. But you do not have to trust me on this. You can compile the program yourself with the source code I've provided. There's not much more that I can do. Closing as Can't Fix
