### ISSUE TITLE
G106 Has Similar Process

### ISSUE THREAD

**Issue by TemporarilyOffline** [DaleFarnsworth/g90updatefw#4]
Hello Dale,

  I have the G106 and there is a very similar process, however it is just different enough that I think we'll need to do some updates to make it work out.  Here is what the G106 returns when you run `g90updatefw`:

```
XG Bootloader(v2.0)
1.Update FW
2.Quit
Exit in 51(s)1
Exit in 48(s)1
```

I pressed 1 and nothing happened, I'm guessing we're not sending user keystrokes to the radio.  

The Serial settings in windows are :

COM4, 8,n,1, No Flow Control, 115200bps

After you press 1, it erases the firmware:

```
XG Bootloader(v2.0)
1.Update FW
2.Quit
Erasing..100%
Wait FW file...
C
```
Then I used terraterm's Xmodem upload to upload the file and the radio finished with this message:

```
Complete!
Please disconnect the power cable and connect it later.
```

Happy to help out with more info as things progress.

I've made this video for the G90: https://youtu.be/NIUbbSjRXsU

**Comment by DaleFarnsworth** [comment]
Hi Steve. The video is nice.

Regarding this issue, I suspect that either g90updatefw is waiting for a different string to appear, or it's trying to send the '1' character too soon and I need to increase the delay before sending the '1'. Please show the full dialog while attempting to update the G106, including the "Waiting for ..." messages.

**Comment by TemporarilyOffline** [comment]
That is the full dialog.  In the old days there was a "waitfor()" function that would look for certain words to come back before responding?  This comes up pretty quickly on boot.  If you want to send me a version with a shorter wait time or a command line parameter, I can test it out.  Could even do a zoom session if you'd like.

**Comment by DaleFarnsworth** [comment]
Now I'm confused. So, on running g90updatefw, it never says:
> 1. Disconnect power cable from radio.
> 2. Reconnect power cable to radio.
> 3. Power-on the radio.
 etc.??

**Comment by TemporarilyOffline** [comment]
Correct, it never says that, just goes straight into `XG  Bootloader...`  I'm uploading a video now, I can give you a sneak peak in a minute.

**Comment by DaleFarnsworth** [comment]
I believe you, but I'm at a loss. After reading the arguments, g90updatefw opens the serial port, reads the firmware file, and then prints those instructions to stdout. I don't know where to go from here.

**Comment by TemporarilyOffline** [comment]
https://www.youtube.com/watch?v=YZ93LIwvp4c

**Comment by DaleFarnsworth** [comment]
Just to clarify, it's the g90updatefw program that should print
> 1. Disconnect power cable from radio.
> 2. Reconnect power cable to radio.
> 3. Power-on the radio.

Then g90updatefw will wait to see "Hit a key to abort" from the radio.
The G90 sends that string, however the G106 does not. That explains why g90updatefw doesn't work with the G106.

I'll try to gen up a version that works with the G106. It will take me a few days to get to it though.

**Comment by TemporarilyOffline** [comment]
No worries, I'm here to test!

**Comment by TemporarilyOffline** [comment]
I get it! I was only sharing the "actual" screen process from the G106.  I'll get some from yours a little later.

**Comment by DaleFarnsworth** [comment]
Okay. I found some time and made a quick version for you to test. Give https://www.farnsworth.org/dale/g90updatefw.exe a try. If you add the --nointerrupt (or -n) option on the command line, it *may* work for the G106. Let me know how it goes.

**Comment by TemporarilyOffline** [comment]
Here is the output from your program: 

```
% ./g90updatefw G106Fw-V1.2b02.xgf /dev/ttyUSB1 
> 1. Disconnect power cable from radio.
> 2. Reconnect power cable to radio.
> 3. Power-on the radio.

> Waiting for 'Hit a key to abort'...

Exit in 0(s))
Normal boot... 
To entering IAP mode, hold volume button when powering on.
```

The text from the G90 and the G106 do not align, but I think the method has enough overlap that we can make this work.

**Comment by TemporarilyOffline** [comment]
The previous comment: https://github.com/DaleFarnsworth/g90updatefw/issues/4#issuecomment-1293842128 was for the old version.

This is for the version you linked here: https://github.com/DaleFarnsworth/g90updatefw/issues/4#issuecomment-1292805207

```
Z:\G106\test>g90updatefw.exe G106Fw-V1.2b02.xgf com4
> 1. Disconnect power cable from radio.
> 2. Reconnect power cable to radio.
> 3. Power-on the radio.

> Waiting for 'Hit a key to abort'...

←[0m←[0m←[2J←[HXG Bootloader(v2.0)
1.Update FW
2.Quit
Exit in 51(s)
```

**Comment by DaleFarnsworth** [comment]
You need to include the -n option i.e.
g90updatefw.exe -n G106Fw-V1.2b02.xgf com4

I'll later modify it so that you won't need that option if you rename the program g106updatefw. I also solicit your suggestion as to what the introductory text should be for the G106.

**Comment by TemporarilyOffline** [comment]
/shrug: 

```
Z:\test>g90updatefw -n G106Fw-V1.2b02.xgf com4
Usage: g90updatefw [--nointerrupt] <firmware_file> <serial_device>
  or   g90updatefw --help
  or   g90updatefw --version

Z:\test>g90updatefw.exe -n G106Fw-V1.2b02.xgf com4
Usage: g90updatefw.exe [--nointerrupt] <firmware_file> <serial_device>
  or   g90updatefw.exe --help
  or   g90updatefw.exe --version

Z:\test>g90updatefw.exe -N G106Fw-V1.2b02.xgf com4
Usage: g90updatefw.exe [--nointerrupt] <firmware_file> <serial_device>
  or   g90updatefw.exe --help
  or   g90updatefw.exe --version
```

**Comment by DaleFarnsworth** [comment]
Thanks. My bad. I'll have a new version up later today.

**Comment by DaleFarnsworth** [comment]
Please try it again. This time download https://www.farnsworth.org/dale/g106updatefw.exe
Run: g106updatefw.exe G106Fw-V1.2b02.xgf com4

I've got my fingers crossed.

**Comment by TemporarilyOffline** [comment]
(404)

**Comment by DaleFarnsworth** [comment]
Sigh. I forget the .exe extension when I copied it. It's there now.

**Comment by DaleFarnsworth** [comment]
Sorry Steve. I realized that one won't work either because of the .exe extension. I won't ask you to test again until I've booted up and tested in windows, which I haven't done for months

**Comment by DaleFarnsworth** [comment]
Okay Steve, I've tested the latest version on Linux and Windows. It's available at https://www.farnsworth.org/dale/g90updatefw.exe and https://www.farnsworth.org/dale/g106updatefw.exe . (They are the same program.)

Here is how the program determines the target radio model to be updated (in order of precedence):
 1. Command line option --g90 or --g106
 2. If the filename of the update contains "g90", "G90", "g106", or "G106".
 3. If the executable program name contains "g90", "G90", "g106", or "G106".

I apologize for not testing on windows previously and am embarrassed by the wasted effort it caused you.
If you can bring yourself to try updating the G106 again, I'd appreciate it.

**Comment by TemporarilyOffline** [comment]
Eureka!

```Z:\test>g106updatefw.exe G106Fw-V1.2b02.xgf com4
Updating firmware for the Xiegu G106 radio.

> 1. Disconnect power cable from the radio.
> 2. Reconnect power cable to the radio.
> 3. Press the volume button and while holding it in,
> 4. Press and hold the power button until the green light turns on.

> Waiting for '1.Update FW'...

←[0m←[0m←[2J←[HXG Bootloader(v2.0)
1.Update FW
2.Quit
Exit in 59(s)
> Waiting for 'Wait FW file'...

Erasing..100%
Wait FW file...
C

> Uploading 194672 bytes.
> ........................................
> ........................................
> ........................................
> ........................................
> ...............................
> Upload complete.
♠
Complete!
Please disconnect the power cable and connect it later.
```

Looks like that did the thing!

**Comment by DaleFarnsworth** [comment]
Thank you for your persistence, Steve. I've pushed the source code to github and the binaries to my website for version 1.3, which includes G106 support. Closing

**Comment by TemporarilyOffline** [comment]
Happy to help out Dale - I figured it was something simple and we nailed it!
