### ISSUE TITLE
g90updatefw segfault

### ISSUE THREAD

**Issue by PiTiLeZarD** [DaleFarnsworth/g90updatefw#8]
Hey,

After downloading the new version I had a segfault, I tried cloning and `make darwin/amd64/g90updatefw` and same that program has a segfault. Don't get much of a log or anything:

```
❯ g90updatefw --help
[1]    61671 segmentation fault  g90updatefw --help
```

I'm on Sonoma 14.3 amd64

**Comment by PiTiLeZarD** [comment]
I had a workging version of this a while back, unfortunately I replaced it with this one. I tried to build previous versions 1.3, 1.4 and 1.5 segfault for me, 1.2 doesn't build

```
❯ make darwin/amd64/g90updatefw
GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o darwin/amd64/g90updatefw
go: cannot find main module, but found .git/config in /Users/jono/Workspaces/tests/g90updatefw
	to create a module there, run:
	go mod init
```

I'll look into it but I'm not a go expert :/

**Comment by PiTiLeZarD** [comment]
Alright: 
```
go mod init g90
go get github.com/dalefarnsworth/go-xmodem/xmodem
go get github.com/pkg/term
make darwin/amd64/g90updatefw
```

and this one doesn't segfault

**Comment by DaleFarnsworth** [comment]
I'm very sorry to hear that. Unfortunately, I have no Mac hardware, so I
don't think I can do much at this time. Sorry.

Dale

**Comment by DaleFarnsworth** [comment]
Thank you. I'll try updating the version on my site.

Dale

**Comment by PiTiLeZarD** [comment]
The issue must be in here somewhere, tough read :)
https://github.com/DaleFarnsworth/g90updatefw/compare/version_1.2...v1.3

I'll try to valgrind it see if I can get some insight on the segfault.

**Comment by DaleFarnsworth** [comment]
I've updated the dependencies. From your previous comment, I think this will fix the segfault on darwin. I'm closing now. Please re-open if you still see problems. Thank you!

**Comment by PiTiLeZarD** [comment]
Hey, I'm about to get a new cable to see if that fixes my g90, but I've pulled the latest changes and I still have a segfault on master. Sorry :/

**Comment by DaleFarnsworth** [comment]
Thanks for letting me know. Have you tried the corresponding executable?
